# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            QCB 508
tagline:          "QCB 508 | Princeton University"
description:      "<a href='https://registrar.princeton.edu/course-offerings/course_details.xml?courseid=014087&term=1174' target='_blank'>Foundations of Applied Statistics and Data Science with Applications in Biology</a>" 
url:              https://jdstorey.github.io
baseurl:          /asdscourse2017

author:
  name:           'John Storey'

paginate:         1000
paginate_path:    "news/page:num/"

markdown:         kramdown

gems:             [jekyll-paginate]

excerpt_separator: <!--more-->

